//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yotelollevo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paquete()
        {
            this.RutaPaquete = new HashSet<RutaPaquete>();
        }
    
        public int IdPaquete { get; set; }
        public int IdTienda { get; set; }
        public string NombreDestinatario { get; set; }
        public string DireccionEntrega { get; set; }
        public int IdComunaEntrega { get; set; }
        public string CelularDestinatario { get; set; }
        public string Comentario { get; set; }
        public int IdEstadoPedido { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Comuna Comuna { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Tienda Tienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RutaPaquete> RutaPaquete { get; set; }
    }
}
