//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yotelollevo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RutaPaquete
    {
        public int IdRutaPaquete { get; set; }
        public int IdRuta { get; set; }
        public int IdPaquete { get; set; }
        public int OrdenEntrega { get; set; }
        public int IdEstadoEntrega { get; set; }
        public Nullable<System.DateTime> HoraEvento { get; set; }
        public string Observacion { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Paquete Paquete { get; set; }
        public virtual Ruta Ruta { get; set; }
    }
}
