//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yotelollevo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ruta()
        {
            this.RutaPaquete = new HashSet<RutaPaquete>();
        }
    
        public int IdRuta { get; set; }
        public System.DateTime FechaRuta { get; set; }
        public int IdRepartidor { get; set; }
        public int IdEstadoRuta { get; set; }
        public string Observacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Repartidor Repartidor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RutaPaquete> RutaPaquete { get; set; }
    }
}
